databases:
  - name: prometei-new-db
    plan: free
    databaseName: prometei_new
    user: prometei_new_user

services:
  - type: web
    plan: starter
    name: prometei-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prometei-new-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_HOSTNAME
        value: prometeylabs.com
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: LANGUAGE_CODE
        value: uk
      - key: SITE_URL
        value: "https://www.prometeylabs.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: "Prometey Labs <info@prometeylabs.com>"
      - key: CONTACT_EMAIL
        value: "info@prometeylabs.com"